Add file parsing
Ecnama/ADSPlanner pull request #2
Opened 2024-11-26 11:20 UTC by Ecnama

This PR adds functions to get a well-formatted dataframe from the spreadsheet file given in input.

2024-11-28 16:18 UTC, pixup1 approved these changes
LGTM !

2024-12-01 09:09 UTC, pixup1 requested changes

2024-12-01 09:09 UTC, pixup1 commented on R/input.R
> +library(readODS)
You need to document these imports inside `ADSPlanner-package.R` and then run `devtools::document()`, or else they won't work when the package is compiled. (Check out my PR)

2024-12-02 09:28 UTC, pixup1 approved these changes
ok lgtm 👍👍👍👍

2024-12-02 11:10 UTC, noemuie approved these changes

2024-12-03 08:04 UTC, merged